AWSTemplateFormatVersion: '2010-09-09'
Description: Creates resources such as SSM parameters used by all stacks

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Configuration
        Parameters:
          - Environment
          - DeploymentBucket
          - GeocoreSslCertArn
          - GeocoreMetadataSslCertArn
          - GeocoreHarvestSslCertArn
          - GeocorePygeoapiSslCertArn
          - GeolocatorSslCertArn
          - TiTilerSslCertArn
          - GeoCaSslCertArn
          - AppGeoCaSslCertArn
          - SearchSslCertArn
          - GithubUsername
          - GithubKey

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
    Default: dev
    Description: Type of App Environment - dev stage prod
  DynamoDBCreationBool:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
    Description: True or false to recreate all dynamodb tables
  DeploymentBucket:
    Description: S3 bucket where all the deployment related files are
    Type: String
    Default: webpresence-deployment-files-dev      
  GeocoreSslCertArn:
    Description: ARN of the SSL cert stored in ACM to be used for Geocore
    Type: String
  GeocoreMetadataSslCertArn:
    Description: ARN of the SSL cert stored in ACM to be used for Geocore Metadata
    Type: String    
  GeocoreHarvestSslCertArn:
    Description: ARN of the SSL cert stored in ACM to be used for Geocore HNAP JSON Harvester
    Type: String
  GeocorePygeoapiSslCertArn:
    Description: ARN of the SSL cert stored in ACM to be used for Geocore pygeoapi
    Type: String
  GeolocatorSslCertArn:
    Description: ARN of the SSL cert stored in ACM to be used for Geolocator
    Type: String
  TiTilerSslCertArn:
    Description: ARN of the SSL cert stored in ACM to be used for TiTiler
    Type: String
  GeoCaSslCertArn:
    Description: ARN of the SSL cert stored in ACM to be used for geo.ca
    Type: String    
  AppGeoCaSslCertArn:
    Description: ARN of the SSL cert stored in ACM to be used for app.geo.ca
    Type: String    
  SearchSslCertArn:
    Description: ARN of the SSL cert stored in ACM to be used for search-recherche.geocore.api.geo.ca
    Type: String    
  GithubUsername: 
    Description: Github Username for accessing Canadian Geospatial Platform
    Type: String
  GithubKey: 
    Description: Github Key for accessing Canadian Geospatial Platform 
    Type: String  

Conditions: 
  IsProd: !Equals [prod, !Ref Environment]
  IsStage: !Equals [stage, !Ref Environment]
  IsDev: !Equals [dev, !Ref Environment]

Resources:

  CloudFrontAccessLogsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'webpresence-cloudfront-access-logs-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      AccessControl: Private

  CloudFrontAccessLogsBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CloudFrontAccessLogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: 
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
          Action: 
            - s3:GetBucketAcl
            - s3:PutBucketAcl
          Resource: !Sub "arn:aws:s3:::webpresence-cloudfront-access-logs-${Environment}"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:PutRetentionPolicy'
                  - 'logs:DescribeSubscriptionFilters'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DeleteSubscriptionFilter'
                  - 'logs:PutSubscriptionFilter'

  LogGroupHelper:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Sub aws-gccp-common/utils/deployment-helpers/deployment-helpers.zip
      Handler: functions/log_group.handler
      Runtime: python3.6
      Timeout: 600
      Role: !GetAtt
        - LambdaExecutionRole
        - Arn

  DeploymentBucketParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: S3 bucket where all the deployment related files are
      Name: /webpresence/deployment-bucket
      Type: String
      Value: !Ref DeploymentBucket
      
  EnvironmentParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Type of App Environment - dev stage prod
      Name: /webpresence/environment
      Type: String
      Value: !Ref Environment

  DynamoDBCreationParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: True or false to recreate all dynamodb tables
      Name: /webpresence/dynamodb_creation
      Type: String
      Value: !Ref DynamoDBCreationBool

  GeocoreHarvestSslCertArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of the SSL cert stored in ACM to be used for Geocore HNAP JSON harvester
      Name: /webpresence/geocore-hnap-harvest/ssl-cert-arn
      Type: String
      Value: !Ref GeocoreHarvestSslCertArn
  
  GeocorePygeoapiSslCertArnParam:
    Condition: IsDev
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of the SSL cert stored in ACM to be used for Geocore pygeoapi
      Name: /webpresence/geocore-pygeoapi/ssl-cert-arn
      Type: String
      Value: !Ref GeocorePygeoapiSslCertArn
      
  GeolocatorSslCertArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of the SSL cert stored in ACM to be used for Geolocator
      Name: /webpresence/geolocator/ssl-cert-arn
      Type: String
      Value: !Ref GeolocatorSslCertArn

  TiTilerSslCertArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of the SSL cert stored in ACM to be used for TiTiler
      Name: /webpresence/titiler/ssl-cert-arn
      Type: String
      Value: !Ref TiTilerSslCertArn

  GeocoreSslCertArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of the SSL cert stored in ACM to be used for Geocore
      Name: /webpresence/geocore/ssl-cert-arn
      Type: String
      Value: !Ref GeocoreSslCertArn

  GeocoreMetadataSslCertArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of the SSL cert stored in ACM to be used for Geocore metadata
      Name: /webpresence/geocore/metadata/ssl-cert-arn
      Type: String
      Value: !Ref GeocoreMetadataSslCertArn

  GeoCaSslCertArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of the SSL cert stored in ACM to be used for geo.ca
      Name: /webpresence/geo-ca/ssl-cert-arn
      Type: String
      Value: !Ref GeoCaSslCertArn

  AppGeoCaSslCertArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of the SSL cert stored in ACM to be used for app.geo.ca
      Name: /webpresence/app-geo-ca/ssl-cert-arn
      Type: String
      Value: !Ref AppGeoCaSslCertArn

  SearchSslCertArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of the SSL cert stored in ACM to be used for search-recherche.geocore.api.geo.ca 
      Name: /webpresence/search-geocore-api-geo-ca/ssl-cert-arn
      Type: String
      Value: !Ref SearchSslCertArn

  GithubUsernameParam:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Github Username for accessing Canadian Geospatial Platform
      Name: /webpresence/github/username
      SecretString: !Ref GithubUsername

  GithubKeyParam:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Github Key for accessing Canadian Geospatial Platform
      Name: /webpresence/github/key
      SecretString: !Ref GithubKey


Outputs:
  LogGroupHelperLambdaArn:
    Value: !GetAtt LogGroupHelper.Arn
    Export:
      Name: LogGroupHelperLambdaArn
