name: Push changes from Stage to Prod

on:
  push:
    branches: [ stage ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initiate - Stage
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
    
    - name: Push changes - Init Prod
      run: git push origin -f stage:prod
